//
//  LocalizeString.swift
//  Loco
//
//  Created by abc on 04/06/18.
//  Copyright © 2018 Quy Technology Pvt Ltd. All rights reserved.
//
import Foundation

let NO = NSLocalizedString("No" ,comment: "No")
let YES = NSLocalizedString("Yes" ,comment: "Yes")
let OK = NSLocalizedString("OK" ,comment: "OK")
let DONE = NSLocalizedString("Done" ,comment: "Done")
let CANCEL = NSLocalizedString("Cancel" ,comment: "Cancel")
let BACK = NSLocalizedString("Back" ,comment: "Back")
let CONFIRM = NSLocalizedString("Confirm" ,comment: "Confirm")
let CONTINUE = NSLocalizedString("Continue" ,comment: "Continue")
let COMMENT = NSLocalizedString("Comment" ,comment: "Comment")
let INVITE = NSLocalizedString("Invite" ,comment: "Invite")
let DONT_INVITE = NSLocalizedString("Don't Invite" ,comment: "Don't Invite")
let INVITE_FRIENDS_DESC = NSLocalizedString("Invite your Friends to your LOCO table" ,comment: "Invite your Friends to your LOCO table")

let SIGNUP_WARNING_TEXT = NSLocalizedString("Please check if you have entered your Date of Birth and Gender truthfully because they cannot be changed later.\nAre you sure you want to proceed ?" ,comment:"Please check if you have entered your Date of Birth and Gender truthfully because they cannot be changed later.\nAre you sure you want to proceed ?")

let NOTIFICATION = NSLocalizedString("Notification" ,comment: "Notification")
let BRING_CITY = NSLocalizedString("Bring LOCO to My City" ,comment: "Bring LOCO to My City")
let NOTIFICATIONS = NSLocalizedString("Notifications" ,comment: "Notifications")
let CHANGE_LANG  = NSLocalizedString("Change Language" ,comment: "Change Language")
let BECOME_HOST = NSLocalizedString("Become a LOCO Host " ,comment: "Become a LOCO Host ")
let BECOME_SPONSOR = NSLocalizedString("Become a LOCO Sponsor" ,comment: "Become a LOCO Sponsor")
let BLOCKED_USERS = NSLocalizedString("Blocked Users" ,comment: "Blocked Users")
let TABLE_FILTERS = NSLocalizedString("Table Filters" ,comment: "Table Filters")
let SHARE_APP = NSLocalizedString("Share App" ,comment: "Share App")
let FEEDBACK = NSLocalizedString("Feedback" ,comment: "Feedback")
let FEEDBACK_MSG = NSLocalizedString("Your feedback is making LOCO better" ,comment: "Your feedback is making LOCO better")

let ABOUT_US = NSLocalizedString("About Us" ,comment: "About Us")
let TERMS_CONDITIONS = NSLocalizedString("Terms & Conditions" ,comment: "Terms & Conditions")
let PRIVACY_POLICY = NSLocalizedString("Privacy Policy" ,comment: "Privacy Policy")
let LOGOUT = NSLocalizedString("Logout" ,comment: "Logout")
let LOGOUT_WARNING = NSLocalizedString("Are you sure you want to logout ?" ,comment: "Are you sure you want to logout ?")
let DELETE = NSLocalizedString("Delete" ,comment: "Delete")
let DELETE_WARNING = NSLocalizedString("Are you sure you want to delete your LOCO account ?" ,comment: "Are you sure you want to delete your LOCO account ?")
let PLZ_FILL_SUBJECT = NSLocalizedString("Please fill the subject" ,comment: "Please fill the subject")
let PLZ_FILL_DESCRIPTION = NSLocalizedString("Please fill out the description" ,comment: "Please fill out the description")
let NO_CONNECTIVITY = NSLocalizedString("No Connectivity" ,comment: "No Connectivity")
let  UNABLE_NETWORK = NSLocalizedString("Please enable your network connection so that we can connect you offline" ,comment: "Please enable your network connection so that we can connect you offline")
let TRY_AGAIN = NSLocalizedString("Try Again", comment: "Try Again")
let MESSAGE = NSLocalizedString("Message" ,comment: "Message")
let ERROR = NSLocalizedString("Error" ,comment: "Error")
let WHY_YOU_WANT_IT = NSLocalizedString("Why you want LOCO ?" ,comment: "Why you want LOCO ?")
let SELECT_COUNTRY = NSLocalizedString("Please select country" ,comment: "Please select country")
let  SELECT_NAME = NSLocalizedString("Please fill the name" ,comment: "Please fill the name")
let CITY_REMARKS = NSLocalizedString("Please fill the city remarks" ,comment: "Please fill the city remarks")
let NAME = NSLocalizedString("Name" ,comment: "Name")
let DOB = NSLocalizedString("Date of Birth" ,comment: "Date of Birth")
let AGE = NSLocalizedString("Age" ,comment: "Age")
let GENDER = NSLocalizedString("Gender" ,comment: "Gender")
let COUNTRY = NSLocalizedString("Country" ,comment: "Country")
let CITY = NSLocalizedString("City" ,comment: "City")
let LOCOLIZER = NSLocalizedString("Locolizer" ,comment: "Locolizer")
let THATS_ME = NSLocalizedString("That’s me" ,comment: "That’s me")
let WARNING = NSLocalizedString("Warning" ,comment: "Warning")
let BACK_WARNING = NSLocalizedString("Data will be lost, Are you sure you want to go back.." ,comment: "Data will be lost, Are you sure you want to go back..")
let EDIT_SAVE_WARNING = NSLocalizedString("Every change will just be saved." ,comment: "Every change will just be saved.")
let LOGIN_WITH_FACEBOOK = NSLocalizedString("LOGIN WITH FACEBOOK" ,comment: "LOGIN WITH FACEBOOK")
let FAILED = NSLocalizedString("Failed" ,comment: "Failed")
let WARNING_FB_LOGIN_FAIL = NSLocalizedString("Fail to login using facebook." ,comment: "Fail to login using facebook.")
let  WARNING_ERROR_LOGIN_FB = NSLocalizedString("Error in facebook login." ,comment: "Error in facebook login.")
let FEMALE = NSLocalizedString("Female" ,comment: "Female")
let ENTER_NAME = NSLocalizedString("Please enter Name" ,comment: "Please enter Name")
let ENTER_DOB = NSLocalizedString("Please enter date of birth" ,comment: "Please enter date of birth")
let PROFILE_PIC = NSLocalizedString("Please select a Profile Picture" ,comment: "Please select a Profile Picture")
let ADD_LANGUAGE = NSLocalizedString("Please add ALL the languages you can speak" ,comment: "Please add ALL the languages you can speak")
let SELECT_CITY = NSLocalizedString("Please select city" ,comment: "Please select city")
let ALERT = NSLocalizedString("Alert" ,comment: "Alert")
let ABOUT_YOURSELF = NSLocalizedString("Write something creative about yourself (min 10 characters)" ,comment: "Write something creative about yourself (min 10 characters)")
let DEVICE_LANGUAGE_TITLE = NSLocalizedString("Please Select Device Language" ,comment: "Please Select Device Language")

let BOOKING_CONFIRMATION = NSLocalizedString("Booking Confirmation" ,comment: "Booking Confirmation")
let REVIEW = NSLocalizedString("Review" ,comment: "Review")
let CONFIRM_BOOK_TABLE_RED_TEXT = "\n\n" + NSLocalizedString("To locolize again, don’t forget to enter the Code you will find at your LOCO table",comment: "To locolize again, don’t forget to enter the Code you will find at your LOCO table")

let INITIAL_TERMS_SERVICES_TEXT = NSLocalizedString("By signing in, you agree with our Terms of Services and Privacy Policy" ,comment:"By signing in, you agree with our Terms of Services and Privacy Policy")
let TERMS_SERVICES = NSLocalizedString("Terms of Services" ,comment: "Terms of Services")
let REPORT_PLACEHOLDER = NSLocalizedString("Specify the reason behind reporting this loconaut.",comment: "Specify the reason behind reporting this loconaut.")
let DELETE_ACCOUNT_PLACEHOLDER = NSLocalizedString("Why do you want to delete your account?",comment: "Why do you want to delete your account?")
let TOAST_PROFILE_UPDATED_MSG = NSLocalizedString("Your information has been updated succesfully.",comment: "Your information has been updated succesfully.")
let TOAST_REPORT_USER_DONE = NSLocalizedString("This loconaut has been reported to admin.",comment: "This loconaut has been reported to admin.")
let TOAST_DELETE_ACCOUNT_REQUEST_DONE = NSLocalizedString("Your request has been submitted successfully.",comment: "Your request has been submitted successfully.")
let PLACEHOLDER_LOCALIZER =  NSLocalizedString("Type in your Locolizer here! This is your icebreaker, which will be displayed to the other loconauts.\nShare something amazing / funny / interesting about you." ,comment: "Type in your Locolizer here! This is your icebreaker, which will be displayed to the other loconauts.\nShare something amazing / funny / interesting about you.")

let HOST_REDIRECT_LOCALIZER =  NSLocalizedString("This could be your advertisement!\nWow, that would be so amazing!" ,comment: "This could be your advertisement!\nWow, that would be so amazing!")

 let DISCOUNT_STRING =  NSLocalizedString("No Discount Available" ,comment: "No Discount Available" )
let DELETE_ACCOUNT = NSLocalizedString("Delete LOCO Account" ,comment: "Delete LOCO Account" )
let Change_Password = NSLocalizedString("Change Password", comment: "Change Password")
let ENTER_CODE_WARNING_TITLE =  NSLocalizedString("Please enter your code to locolize again" ,comment: "Please enter your code to locolize again" )
   // let ENTER_CODE_WARNING_MESSAGE = NSLocalizedString("Please enter your previous table code." ,comment: "Please enter your previous table code." )

let COUNTRY_MESSAGE = NSLocalizedString("Please choose country ",comment : "Please choose country ")
let CITY_MESSAGE = NSLocalizedString("Please choose city ",comment : "Please choose city ")

let UNBLOCK               = NSLocalizedString("Unblock",comment : "Unblock")
let UNBLOCK_ALERT_MESSAGE = NSLocalizedString("Are you sure you want to unblock this user?",comment : "Are you sure you want to unblock this user?")
let BLOCK                 = NSLocalizedString("Block",comment : "Block")
let BLOCK_USER            = NSLocalizedString("Block User!",comment : "Block User!")
let BLOCK_USER_MESSAGE    = NSLocalizedString("Are you sure you want to block this Loconaut?",comment : "Are you sure you want to block this Loconaut?")
let USER_ALREADY_INVITED  = NSLocalizedString("User is already invited.",comment : "User is already invited.")
let SELECT_USER           = NSLocalizedString("Please select atleast one user.",comment : "Please select atleast one user.")
let ACCEPT                = NSLocalizedString("Accept",comment : "Accept")
let DECLINE               = NSLocalizedString("Decline",comment : "Decline")
let ACCEPTED              = NSLocalizedString("Accepted",comment : "Accepted")
let DECLINED              = NSLocalizedString("Declined",comment : "Declined")
let CLOSED                = NSLocalizedString("Closed",comment : "Closed")
let NUMBER_NOT_AVAILABLE  = NSLocalizedString("Contct number is not available.",comment : "Contct number is not available.")
let MESSAGE_NOT_AVAILABLE = NSLocalizedString("Messaging is not available.",comment : "Messaging is not available.")
let INVITED               = NSLocalizedString("Invited",comment : "Invited")
let SHARE                 = NSLocalizedString("Share",comment : "Share")
let NOT_JOINED            = NSLocalizedString("Not Joined",comment : "Not Joined")
let UNCONDITIONAL         = NSLocalizedString("Unconditional",comment : "Unconditional")
let CONDITIONAL           = NSLocalizedString("Conditional",comment : "Conditional")
let INVITE_BACK_WARNING   = NSLocalizedString("Your Loconaut invitation will be lost. Are you sure you want to leave this page?", comment: "Your Loconaut invitation will be lost. Are you sure you want to leave this page?")
let BLOCK_BY_INVITEE      = NSLocalizedString("You can't invite as you are blocked by this user", comment: "You can't invite as you are blocked by this user")

let DEVICE_LOCATION_DISABLED = NSLocalizedString("Please enable the device location services", comment: "Please enable the device location services")
let USER_ALREADY_INVITED_BY_SOMEONE  = NSLocalizedString("User is already invited by someone else.",comment : "User is already invited by someone else.")
let USER_ALREADY_BOOKED  = NSLocalizedString("User is already booked for this table.",comment : "User is already booked for this table.")
let ALREADY_INVITED = NSLocalizedString("Currently you already have invited loconauts to another LOCO table. You can not book multiple tables in parallel",comment : "Currently you already have invited loconauts to another LOCO table. You can not book multiple tables in parallel")
let NO_INVITATION = NSLocalizedString("You have no invitation", comment: "You have no invitation")
let NOT_FOUND_LOCOTABLES = NSLocalizedString("We have not found any LOCO tables. Please consider adjusting your search filters or the languages in your profiles", comment: "We have not found any LOCO tables. Please consider adjusting your search filters or the languages in your profiles")
let ENABLE_CAMERA_SETTINGS = NSLocalizedString("Please enable the camera access settings.", comment: "Please enable the camera access settings.")
let ABOUT_TO_BOOK = NSLocalizedString("You are about to book the following LOCO table", comment: "You are about to book the following LOCO table") + "\n\n"
let CONFIRM_LOCOTABLE = "\n" + NSLocalizedString("Confirm your LOCO table", comment: "Confirm your LOCO table") + "\n"
let YAY = NSLocalizedString("Yay!", comment: "Yay!")
let SENT_YOU_INVITATION_FOR_TABLE = NSLocalizedString("has invited you to join this LOCO table", comment: "has invited you to join this LOCO table")
let HOST = NSLocalizedString("Host", comment: "Host")
let LOOKING_FORWARD_TO_MEET = NSLocalizedString("is looking forward to meeting you there!", comment: "is looking forward to meeting you there!")
let ENTER_RECEIVED_CODE = NSLocalizedString("Please enter the Code received by the host", comment: "Please enter the Code received by the host")
let INVALID_CODE = NSLocalizedString("Invalid CODE", comment: "Invalid CODE")
let ENTER_TABLE_CODE = NSLocalizedString("Before booking your next table, please enter the code of your last table or wait for %@to locolize again.", comment: "Before booking your next table, please enter the code of your last table or wait for %@to locolize again.")
let INVITE_THIS_LOCONAUT = NSLocalizedString("Invite This Loconaut", comment: "Invite This Loconaut")
let LOCONAUT_INVITED = NSLocalizedString("Loconaut Invited", comment: "Loconaut Invited")

let YEARS = NSLocalizedString("years", comment: "years")
let YEAR = NSLocalizedString("year", comment: "year")
let MONTHS = NSLocalizedString("months", comment: "months")
let MONTH = NSLocalizedString("month", comment: "month")
let DAYS = NSLocalizedString("days", comment: "days")
let DAY = NSLocalizedString("day", comment: "day")
let HOURS = NSLocalizedString("hours", comment: "hours")
let HOUR = NSLocalizedString("hour", comment: "hour")
let MINUTES = NSLocalizedString("minutes", comment: "minutes")
let MINUTE = NSLocalizedString("minute", comment: "minute")
